//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BayesianUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criteria
    {
        public int id { get; set; }
        public string learningStyle { get; set; }
        public string initialUnderstanding { get; set; }
        public string learningMedia { get; set; }
        public string numberOfStudents { get; set; }
        public string learningMethod { get; set; }
    }
}
